server:
  port: 8090  # 원하는 포트 번호로 설정
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sinhyeyeon
    password: hyhy
  logging:
    level:
      root: INFO
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
jwt:
  secret: c2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tYW5kLXZhbGlkYXRpb24=